version: '3.8'

services:

  clamav:

    image: clamav/clamav:latest 
    container_name: clamav 
    hostname: calmav
    stop_grace_period: 10s

    environment:
      LANG: en_US.UTF-8

    ports:
      - 3310:3310 

    networks:
      server_net:

  c-icap:

    image: nashcom/c-icap 
    container_name: c-icap 
    hostname: ${ICAP_HOSTNAME} 
    stop_grace_period: 10s

    environment:
      LANG: en_US.UTF-8

    ports:
      - 1344:1344
      - 11344:11344

    volumes:
      - /local/cert.pem:/cert.pem:ro
      - /local/key.pem:/key.pem:ro

    networks:
      server_net:

    depends_on:
      clamav:
        condition: service_healthy

networks:

  server_net:
    driver: bridge
